version: '3.0'

services:
  db:
    container_name: mysql_db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=test_db # name you want for the database
      - MYSQL_USER=username # change to whatever username you want
      - MYSQL_PASSWORD=password #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=password #change to good root password
    ports:
      - "3306:3306"

  web:
    container_name: django-views
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"